inferno-framework/us-core-test-kit

- spec/us_core/must_support_test_spec.rb
This PR adds more spec tests for
* missing MS element
* missing MS extension
* missing MS slice
> FI-1528 Add must_support spec tests

- lib/us_core_test_kit/custom_groups/clinical_note_type_test.rb
- spec/us_core/clinical_note_type_test_spec.rb
This PR address GitHub Issue https://github.com/onc-healthit/onc-certification-g10-test-kit/issues/113
The changes include:
* Update clinical_note_type_test to filter DiagnosticReport with required categories only
* Update clinical_note_type_test to not save attachment without url
* Add unit test
> FI-1554 clinical note attachment

- lib/us_core_test_kit/search_test.rb
This PR fixes GitHub Issue https://github.com/onc-healthit/onc-certification-g10-test-kit/issues/141
The changes are:
* Remove validation of resource types in Bundle search result.
> FI-1595 Remove resource type check

- CHANGELOG.md
- Gemfile.lock
- lib/us_core_test_kit/version.rb
> Release 0.3.0

- README.md
* Add note about support for the US Core Implementation Guide 5.0.1
> Add US Core IG 5.0.1 Callout

- .env
- .env.development
- .env.production
- Gemfile
- Gemfile.lock
- Procfile
- config/nginx.background.conf
- docker-compose.background.yml
- docker-compose.yml
https://github.com/inferno-framework/inferno-template/releases/tag/v0.0.3
> FI-1787: Update to use core dev improvements

- lib/us_core_test_kit/reference_resolution_test.rb
- spec/us_core/reference_resolution_test_spec.rb
This PR saves the reference with the profiles it is validated with
> FI:1818: Save resolved reference with target_profiles

- .env.development
- .env.production
Fix for redirecting back to Inferno after SMART Authentication
> Add INFERNO_HOST to .env files

- lib/us_core_test_kit/custom_groups/smart_scopes_constants.rb
- lib/us_core_test_kit/generated/v6.1.0/granular_scope_tests/condition/metadata.yml
- lib/us_core_test_kit/generated/v6.1.0/granular_scope_tests/observation/metadata.yml
- lib/us_core_test_kit/generated/v6.1.0/granular_scopes1_group.rb
- lib/us_core_test_kit/generated/v6.1.0/observation_granular_scope1_group.rb
- lib/us_core_test_kit/generated/v7.0.0-ballot/granular_scope_tests/condition/metadata.yml
- lib/us_core_test_kit/generated/v7.0.0-ballot/granular_scope_tests/diagnostic_report/metadata.yml
- lib/us_core_test_kit/generated/v7.0.0-ballot/granular_scope_tests/document_reference/metadata.yml
- lib/us_core_test_kit/generated/v7.0.0-ballot/granular_scope_tests/observation/metadata.yml
- lib/us_core_test_kit/generated/v7.0.0-ballot/granular_scope_tests/service_request/metadata.yml
- lib/us_core_test_kit/generated/v7.0.0-ballot/metadata.yml
Add a missing Observation scope for US Core 6 granular scopes.
> FI-2371: Add additional granular scope

- lib/us_core_test_kit/custom_groups/screening_assessment_category_test.rb
- lib/us_core_test_kit/custom_groups/v6.1.0/screening_assessment_group.rb
- lib/us_core_test_kit/custom_groups/v7.0.0-ballot/screening_assessment_group.rb
- lib/us_core_test_kit/generated/v6.1.0/us_core_test_suite.rb
- lib/us_core_test_kit/generated/v7.0.0-ballot/us_core_test_suite.rb
- lib/us_core_test_kit/generator/suite_generator.rb
- lib/us_core_test_kit/generator/templates/suite.rb.erb
- spec/us_core/screening_assessment_category_test_spec.rb
This PR fixes Github Issue https://github.com/onc-healthit/onc-certification-g10-test-kit/issues/508.
This JIRA ticket https://jira.hl7.org/browse/FHIR-45319 only address US Core v6.1.0. The mapping for US Core v7 is more complicated and will be addressed by a separated HL7 FHIR ticket. At this time, US Core v7-ballot Test Suite will use the same resolution as US Core v6.1.0
* Add special test Screening Assessment Guidance to US Core v6.1.0 and v7.0.0-ballot Test Suite
* Add Unit tests
Run US Core v6.1.0 Test Suite
Run Test 2.49 "Screening and Assessment Guidance"
> FI-2749 Screen Assessment

- CHANGELOG.md
- Gemfile.lock
- lib/us_core_test_kit/version.rb
Update ChangeLog
Update version
Update Gemfile.lock
> Release 0.7.2

- CHANGELOG.md
- Gemfile.lock
- lib/us_core_test_kit/version.rb
Updated ChangeLog.md
Updated Gemfile.lock
Updated version.rb
> Release 0.8.0

- lib/us_core_test_kit/search_test.rb
- spec/us_core/search_test_spec.rb
This PR fixes github issue https://github.com/onc-healthit/onc-certification-g10-test-kit/issues/557
All unit tests pass
> FI-3508 Retrieve primitive value from navigation result

- CHANGELOG.md
- Gemfile.lock
- lib/us_core_test_kit/version.rb
> Release 0.8.2

- CHANGELOG.md
- Gemfile.lock
- lib/us_core_test_kit/version.rb
Release of US Core Test Kit v0.9.1
> Release 0.9.1

- CHANGELOG.md
- Gemfile.lock
- lib/us_core_test_kit/version.rb
- us_core_test_kit.gemspec
US Core Test Kit Release 0.9.2
> Release 0.9.2

- CHANGELOG.md
- Gemfile.lock
- lib/us_core_test_kit/version.rb
This PR is for US Core Test Kit v0.9.3
* Updated Change Log
* Updated version.rb
> Release v0.9.3

- docs/Version-Update-Guide.md
- docs/_Sidebar.md
When looking up some information I noticed some minor issues.  See diff to see the minor changes.
I already ran the 'Publish Wiki Docs' workflow so it is already synchronized over here: https://github.com/inferno-framework/us-core-test-kit/wiki/Version-Update-Guide
> FI-3471 Minor fixes to docs based on usage

- CHANGELOG.md
- Gemfile.lock
- lib/us_core_test_kit/version.rb
Update Change Log, and version.rb for Release v0.11.1
> Release v0.11.1

- CHANGELOG.md
- Gemfile.lock
- lib/us_core_test_kit/version.rb
- us_core_test_kit.gemspec
Prepare for US Core Test Kit v0.11.2 release for ASTP/ONC Enforcement Discretion
> US Core Release v0.11.2

- CHANGELOG.md
- Gemfile.lock
- lib/us_core_test_kit/version.rb
- us_core_test_kit.gemspec
> Release 0.11.4

- README.md
- docs/README.md
- docs/Version-Update-Guide.md
Add v8.0.0 to both README files.
Update Version Update Guide to pointing the three files need to be updated for new versions
> FI-4214 Add US Core v8 to README

- us_core_test_kit.gemspec
> FI-4182 Remove inferno@groups.mitre.org email from gemspec

- spec/us_core/clinical_note_attachment_test_spec.rb
- spec/us_core/document_reference_custodian_test_spec.rb
- spec/us_core/granted_granular_scopes_test_spec.rb
- spec/us_core/granular_scope_read_spec.rb
- spec/us_core/granular_scope_search_spec.rb
- spec/us_core/instantiate_test_spec.rb
- spec/us_core/interpreter_required_extension_test_spec.rb
- spec/us_core/must_support_test_spec.rb
- spec/us_core/practitioner_address_test_spec.rb
- spec/us_core/profile_support_test_spec.rb
- spec/us_core/reference_test_spec.rb
- spec/us_core/screening_assessment_category_test_spec.rb
- spec/us_core/search_test_spec.rb
- spec/us_core/smart_well_known_capabilities_test_sepc.rb
- spec/us_core/us_core_v311_resource_support_test_spec.rb
- spec/us_core/validation_test_spec.rb
- Replaces local code with helpers from inferno core rspec support
1. Checkout branch
2. `bundle exec rspec`
> FI-3815: Update Test Kit with new RSpec features
