inferno-framework/us-core-test-kit

- lib/us_core/generated/us_core_test_suite.rb
- lib/us_core/generator/templates/suite.rb.erb
Use `oauth_credentials` so that access tokens can automatically refresh.
> FI-1407: Use oauth_credentials

- lib/us_core/search_test.rb
This migrate FI-1406 from Inferno Program. The change allows case insensitive comparison for CodeableConcept and Coding data type
> Migrate FI-1406 Allow case insensitive token comparison

- lib/us_core/generated/bodyheight/bodyheight_must_support_test.rb
- lib/us_core/generated/bodyheight/metadata.yml
- lib/us_core/generated/bodytemp/bodytemp_must_support_test.rb
- lib/us_core/generated/bodytemp/metadata.yml
- lib/us_core/generated/bodyweight/bodyweight_must_support_test.rb
- lib/us_core/generated/bodyweight/metadata.yml
- lib/us_core/generated/bp/bp_must_support_test.rb
- lib/us_core/generated/bp/metadata.yml
- lib/us_core/generated/heartrate/heartrate_must_support_test.rb
- lib/us_core/generated/heartrate/metadata.yml
- lib/us_core/generated/metadata.yml
- lib/us_core/generated/observation_lab/metadata.yml
- lib/us_core/generated/observation_lab/observation_lab_must_support_test.rb
- lib/us_core/generated/pulse_oximetry/metadata.yml
- lib/us_core/generated/pulse_oximetry/pulse_oximetry_must_support_test.rb
- lib/us_core/generated/resprate/metadata.yml
- lib/us_core/generated/resprate/resprate_must_support_test.rb
- lib/us_core/generator/must_support_metadata_extractor.rb
This PR migrate https://github.com/onc-healthit/inferno-program/pull/354 to Inferno 2.0 uscore-test-kit.
Changes:
Add component MS check back to BP profile
Remove dataAbsentReason and component.dataAbsentReson for Observtion profiles
> FI-1304 Adding Observation.component MS check for BP profile. Remove dataAbsentReason MS check from Observation profiles

- lib/us_core/generated/smokingstatus/smokingstatus_patient_category_date_search_test.rb
- lib/us_core/generated/smokingstatus/smokingstatus_patient_category_search_test.rb
- lib/us_core/generator/search_test_generator.rb
Some search combinations are required in CapabilityStatement for Observation but SmokingStatus profile does have all search element as required or MustSupport.
Change those search combinations from required search test to optional search test
> FI-1459 Fix Smoking Status search

- lib/us_core/read_test.rb
This branch adds a configuration option for read tests to allow them to read all resources. Generally, it's only necessary to read one resource to verify that the read interaction works. In the g10 test kit, however, there are some groups where the searches are not performed, so multiple resources need to be read in order to adequately check for the presence of must support elements.
> FI-1464: Allow read tests to be configured to read all resources

- lib/us_core_test_kit/generated/v3.1.1/device/device_must_support_test.rb
- lib/us_core_test_kit/generated/v3.1.1/device/metadata.yml
- lib/us_core_test_kit/generated/v3.1.1/document_reference/document_reference_must_support_test.rb
- lib/us_core_test_kit/generated/v3.1.1/document_reference/metadata.yml
- lib/us_core_test_kit/generated/v3.1.1/metadata.yml
- lib/us_core_test_kit/generated/v4.0.0/document_reference/document_reference_must_support_test.rb
- lib/us_core_test_kit/generated/v4.0.0/document_reference/metadata.yml
- lib/us_core_test_kit/generated/v4.0.0/encounter/metadata.yml
- lib/us_core_test_kit/generated/v4.0.0/medication_request/metadata.yml
- lib/us_core_test_kit/generated/v4.0.0/metadata.yml
- lib/us_core_test_kit/generator/must_support_metadata_extractor.rb
- lib/us_core_test_kit/must_support_test.rb
- spec/fixtures/device_metadata.yml
- spec/us_core/must_support_test_spec.rb
US Core use narrative section to fine turn some MustSupport elements, such as:
Although both are marked as must support, servers are not required to support both Encounter.location.location and Encounter.serviceProvider, but they SHALL support at least one of these elements.
This PR added "choices" to metadata to indicate which elements are in the choice pair. For example, in the encounter's metadata.yml
```
:must_supports:
:choices:
- :paths:
- location.location
- serviceProvider
```
must_support_test remove a miss element is it is one of the choice element and the other choice element is not missing.
This PR shall be reviewed and merged after PR #17
> FI-1502 Handles Must Support Choice

- lib/us_core_test_kit/search_test.rb
Fix an incorrectly escaped string interpolation which prevents absolute urls from matching search parameters. Raised in https://github.com/onc-healthit/onc-certification-g10-test-kit/issues/63
> FI-1514: Fix escaped string interpolation

- lib/us_core_test_kit/read_test.rb
Issue raised in https://github.com/onc-healthit/onc-certification-g10-test-kit/issues/71
We're mistakenly adding the test id rather than the resource id to the error message. I added `inspect` to the message so that it will be possible to differentiate between strings and integers in the message.
> FI-1523: Fix error message in read tests when id does not match

- lib/us_core_test_kit/custom_groups/clinical_note_attachment_test.rb
- spec/us_core/clinical_note_attachment_test_spec.rb
This PR fixes GitHub Issue https://github.com/onc-healthit/onc-certification-g10-test-kit/issues/110
It merges changes from PR #36 and add a unit test.
> Fix the failure when Clinical Note Reference test found non-matched reference

- README.md
- lib/us_core_test_kit/generated/v4.0.0/metadata.yml
- lib/us_core_test_kit/generated/v4.0.0/patient/metadata.yml
- lib/us_core_test_kit/generated/v4.0.0/patient/patient_must_support_test.rb
- lib/us_core_test_kit/generator/must_support_metadata_extractor.rb
This PR updates testing logic for patient's previous name MustSupport test
* US Core 4.0 does not list patient's previous name as a MustSupport in StructureDefinition
* US Core 4.0 mentioned patient's previous as "Additional USCDI requirement"
* US Core 4.0 states that "Previous name is represented by providing an end date in the Patient.name.period element for a previous name."
* ONC CCG clarifies that "Either the US Core IG Profile “StructureDefinition-us-core-patient” element “name.period” or “name.use” is required for testing and certification in the ONC Certification Program to meet the USCDI requirement to support the “Patient Demographics” data class: “Previous Name” data element"
This PR includes
* Adds both name.period.end and name.use:old as MustSupport elements
* Adds …
> FI-1557 Fix Patient's previous name Must Support test

- lib/us_core_test_kit/generated/v3.1.1/device/device_must_support_test.rb
- lib/us_core_test_kit/generated/v3.1.1/document_reference/document_reference_must_support_test.rb
- lib/us_core_test_kit/generated/v4.0.0/document_reference/document_reference_must_support_test.rb
- lib/us_core_test_kit/generated/v4.0.0/encounter/encounter_must_support_test.rb
- lib/us_core_test_kit/generated/v4.0.0/medication_request/medication_request_must_support_test.rb
- lib/us_core_test_kit/generated/v4.0.0/metadata.yml
- lib/us_core_test_kit/generated/v4.0.0/patient/metadata.yml
- lib/us_core_test_kit/generated/v4.0.0/patient/patient_must_support_test.rb
- lib/us_core_test_kit/generator/must_support_metadata_extractor.rb
- lib/us_core_test_kit/generator/must_support_test_generator.rb
- lib/us_core_test_kit/generator/templates/must_support.rb.erb
- lib/us_core_test_kit/must_support_test.rb
USCore v4.0 starts separation of USCDI requirements into "Additional USCDI requirement" narrative section. 
This PR changes
* Add uscdi_only tag to those USCDI requirements 
* Add logic in must_support_test to load or not load USCDI tests based on configuration
* Update Must Support test description to concatenate MustSupport choices with "or"
This PR depends on #43
> FI-1585 Separate USCDI requirements from USCore requirements

- lib/us_core_test_kit/search_test.rb
- spec/us_core/search_test_spec.rb
This PR fixes GitHub Issue https://github.com/onc-healthit/onc-certification-g10-test-kit/issues/136
This PR include
* Fixes the logic in search_test.rb when generating search values for non-multiple-or status search
* Adds Unit test.
> FI-1587 Encounter status search

- lib/us_core_test_kit/fhir_resource_navigation.rb
- lib/us_core_test_kit/search_test.rb
- spec/us_core/search_test_spec.rb
This PR fixes part of GitHub Issue https://github.com/onc-healthit/onc-certification-g10-test-kit/issues/142
The changes includes
* Add parameter `include_dar: false` to method `find_a_value_at`. The method skips element with DAR extension when  `include_dar == false`
* Add unit test to cover this use case
Testing
* A unit test was created to cover the use case. The simplest testing is observing all unit tests pass
* To run integration test:
** Create a patient with name having DAR as the first item. Example
```
"name": [
{
"extension": [
{
"url": "http://hl7.org/fhir/StructureDefinition/data-absent-reason",
"valueCode": "unknown"
}
]
},
{
"use": "official",
"text": "Johnny LastName",
"family": "LastName",
"given": [
"Johnny"
]
}
],
```
** Run the Patient Tests (Test Group 2) and verify …
> FI-1599 Skip array item with DAR extension

- lib/us_core_test_kit/search_test.rb
- spec/us_core/search_test_spec.rb
This PR fixes part of GitHub Issue https://github.com/onc-healthit/onc-certification-g10-test-kit/issues/138
This PR include these changes
* Retrieve values for multiple search parameters from one resource
* Skip these elements when retrieving search values for existing resources
** CodeableConcept without `coding` 
** Reference without `reference` 
** Coding without `code` and/or `system`
** Identifier without `value` and/or `system`
** HumanName without `family`, `given`, and `text`
** Address without `text`, `city`, `state`, `postCode`, and `country`
Testing
* Multiple unit tests are added to cover the code changes
> FI-1604 Fix how Inferno Generate search value

- .gitignore
- lib/us_core_test_kit/search_test.rb
- spec/us_core/search_test_spec.rb
This PR fixes GitHub Issue https://github.com/onc-healthit/onc-certification-g10-test-kit/issues/171
The changes include
* Filter result of `fetch_all_bundled_resources` with `resource_type`
* Add unit test
> Filter bundle result for comparator search

- lib/us_core_test_kit/generated/v4.0.0/metadata.yml
- lib/us_core_test_kit/generated/v4.0.0/patient/metadata.yml
- lib/us_core_test_kit/generated/v4.0.0/patient/patient_must_support_test.rb
- lib/us_core_test_kit/generator/must_support_metadata_extractor.rb
This issue was found while doing US Core v5 development.
These elements are marked as MS in US Core profiles and should NOT have the `uscdi-only` label.
Patient.telecom.system
Patient.telecom.value
Patient.telecom.use
Patient.communication.language
> US Core 4.0 Move Patient.telecom.* and Patient.communicaiton.* out of USCDI

- lib/us_core_test_kit/must_support_test.rb
- spec/us_core/must_support_test_spec.rb
This PR fixes GitHub Issue https://github.com/onc-healthit/onc-certification-g10-test-kit/issues/178
The root cause is that US Core must_support_test checks slicing of Date and String but not DateTime.
This PR affects US Core 4.0.0 Test Kit and US Core 5.0.1 Test Kit. It does NOT affect US Core 3.1.1 Test Kit.
The change include:
* Adds MustSupport test of slicing with type 'DateTime' 
* Adds Unit Test
> FI-1657 Add must support test for datetime slicing

- .env
This just adds an explicit validator url for v501 as an environment variable.  It defaulted to the same spot, but this helps discoverability of this env variable and makes it consistent with the other versions.
Used here: https://github.com/inferno-framework/us-core-test-kit/blob/2063f6c1e719a291f5f63c54b28912e03d5ee765/lib/us_core_test_kit/generated/v5.0.1/us_core_test_suite.rb#L67
Just launch and make sure that this doesn't brake validation.
> Add V501 validator to env for completeness.

- lib/us_core_test_kit/custom_groups/v4.0.0/device_udi_pi_test.rb
- lib/us_core_test_kit/custom_groups/v4.0.0/document_reference_custodian_test.rb
- lib/us_core_test_kit/read_test.rb
- lib/us_core_test_kit/reference_resolution_test.rb
This PR fixes Github Issue https://github.com/onc-healthit/onc-certification-g10-test-kit/issues/236
Run US Core test kit with patient/85 alone.
Verify that skip messages have the correct spelling
> FI-1695 Fix the typo

- lib/us_core_test_kit/reference_resolution_test.rb
- spec/us_core/reference_resolution_test_spec.rb
- spec/us_core/reference_test_spec.rb
This is to resolve GitHub Issue https://github.com/onc-healthit/onc-certification-g10-test-kit/issues/240
The issue does NOT affect the testing result but could add confusion validation errors in the message area.
A Reference element may have many references. For example, DiagnosticReport.performer (for Note Exchange, v4.0.0) has 4 target references (Practitioner | Organization | PractitionerRole | CareTeam). Only the first two are Must Supported and covered by Reference validation test. 
Reference validation test need to find ONE reference that the referenced resource is valid with target profile. When the referenced resource is a CareTeam, the validation report error and test skips this reference. 
This PR changes the method `resource_is_valid_with_target_profile` to call …
> FI-1703 reference validation

- lib/us_core_test_kit/generated/v5.0.1/questionnaire_response/metadata.yml
- lib/us_core_test_kit/generated/v5.0.1/questionnaire_response/questionnaire_response_id_search_test.rb
- lib/us_core_test_kit/generated/v5.0.1/questionnaire_response/questionnaire_response_must_support_test.rb
- lib/us_core_test_kit/generated/v5.0.1/questionnaire_response/questionnaire_response_patient_authored_search_test.rb
- lib/us_core_test_kit/generated/v5.0.1/questionnaire_response/questionnaire_response_patient_questionnaire_search_test.rb
- lib/us_core_test_kit/generated/v5.0.1/questionnaire_response/questionnaire_response_patient_search_test.rb
- lib/us_core_test_kit/generated/v5.0.1/questionnaire_response/questionnaire_response_patient_status_search_test.rb
- lib/us_core_test_kit/generated/v5.0.1/questionnaire_response/questionnaire_response_patient_tag_authored_search_test.rb
- lib/us_core_test_kit/generated/v5.0.1/questionnaire_response/questionnaire_response_patient_tag_search_test.rb
- lib/us_core_test_kit/generated/v5.0.1/questionnaire_response/questionnaire_response_provenance_revinclude_search_test.rb
- lib/us_core_test_kit/generated/v5.0.1/questionnaire_response/questionnaire_response_read_test.rb
- lib/us_core_test_kit/generated/v5.0.1/questionnaire_response/questionnaire_response_reference_resolution_test.rb
- lib/us_core_test_kit/generated/v5.0.1/questionnaire_response/questionnaire_response_validation_test.rb
- lib/us_core_test_kit/generated/v5.0.1/questionnaire_response_group.rb
- lib/us_core_test_kit/generated/v5.0.1/us_core_test_suite.rb
- lib/us_core_test_kit/generator/group_generator.rb
- lib/us_core_test_kit/generator/special_cases.rb
- lib/us_core_test_kit/generator/templates/group.rb.erb
We had discussion to drop QuestionnaireResponse from US Core test kit v5.0.1 because it is a MAY support profile. After discussion, we decide to add it back as an optional test group.
Launch US Core v5.0.1 test kit
Observe that US Core QuestionnaireResponse is listed with Optional tag
> FI-1686 Add US Core QuestionnaireResponse as an optional test group

- lib/us_core_test_kit/reference_resolution_test.rb
- spec/us_core/reference_test_spec.rb
This is to fix Github Issue (https://github.com/onc-healthit/onc-certification-g10-test-kit/issues/261)
reference_resolution test failed to handle v3.1.1 profiles without target_profile choices.
Changes include
* Add `&` to handle the  choices hash without target_profiles key
* Add unit test to simulate the failed test mentioned in the GitHub Issue
All unit tests passed
> FI-1711 Fix the failure when target_profiles is nil

- lib/us_core_test_kit/generated/v5.0.1/metadata.yml
- lib/us_core_test_kit/generated/v5.0.1/observation_sdoh_assessment/metadata.yml
- lib/us_core_test_kit/generator/must_support_metadata_extractor.rb
Applies US Core Ticket FI-37794 (https://jira.hl7.org/browse/FHIR-37794)
The changes is:
Remove US Core QuestionnaireResponse as choices of target profiles for US Core Observation Survey and US Core SDOH Assessment profiles
Verified that metadata.yml of US Core SDOH Assessment profile does not have us-core-questionnairereponse in the must-support section.
> Remove QuestionnaireResponse from MS target profiles

- lib/us_core_test_kit/generated/v4.0.0/metadata.yml
- lib/us_core_test_kit/generated/v4.0.0/smokingstatus/metadata.yml
- lib/us_core_test_kit/generated/v4.0.0/smokingstatus/smokingstatus_patient_category_date_search_test.rb
- lib/us_core_test_kit/generated/v5.0.1/metadata.yml
- lib/us_core_test_kit/generated/v5.0.1/smokingstatus/metadata.yml
- lib/us_core_test_kit/generated/v5.0.1/smokingstatus/smokingstatus_patient_category_date_search_test.rb
- lib/us_core_test_kit/generator/group_metadata_extractor.rb
This PR address a slide line issue found while investigating in GitHub issue https://github.com/onc-healthit/onc-certification-g10-test-kit/issues/262
Update the group_metadata_extractor so that the slice path `Observation.effective[x]:effectiveDateTime` can match to search parameters with expression `Observation.effective` or `Observation.effectiveDateTime`.
in US Core v4.0.0 and v5.0.1, The Observation search by patient+category+code shows as a mandatory test.
> Add search parameter expression match to must support base path

- lib/us_core_test_kit/generated/v4.0.0/metadata.yml
- lib/us_core_test_kit/generated/v4.0.0/patient/metadata.yml
- lib/us_core_test_kit/generated/v4.0.0/patient/patient_must_support_test.rb
- lib/us_core_test_kit/generated/v5.0.1/metadata.yml
- lib/us_core_test_kit/generated/v5.0.1/patient/metadata.yml
- lib/us_core_test_kit/generated/v5.0.1/patient/patient_must_support_test.rb
- lib/us_core_test_kit/generator/must_support_metadata_extractor.rb
This PR addresses GitHub Issue https://github.com/onc-healthit/onc-certification-g10-test-kit/issues/283
The changes includes:
US Core v4.0.0: change Patient's Previous Name MS test from "name.period.end or name.use" to "name.period.end"
US Core v5.0.1: change Patient's Previous Name MS test from "name.period.end or name.use" to "name.period.end AND name.use"
1. Run the US Core v4.0.0 Test Kit. 
2. Expand Test 2.11 "All must support elements are provided in the Patient resources returned". 
3. Verify the "About" tab have: "Patient.name.period.end"
4. Verify the "About" tab does NOT have "Patient.name.period.end or Patient.name.use"
1. Run the US Core v5.0.1 Test Kit. 
2. Expand Test 2.11 "All must support elements are provided in the Patient resources returned". 
3. Verify the "About" tab …
> FI-1739 Update MustSupport test for Patient's previous name

- lib/us_core_test_kit/search_test.rb
- spec/us_core/search_test_spec.rb
This PR fixes GitHub Issue https://github.com/onc-healthit/onc-certification-g10-test-kit/issues/314
Chang Log:
* Updates search_test to use unescaped search value when checking result against parameter
* Adds unit test
All unit tests passed
> FI-1768 Unescape search value

- lib/us_core_test_kit/generated/v3.1.1/document_reference/document_reference_must_support_test.rb
- lib/us_core_test_kit/generated/v3.1.1/document_reference/document_reference_reference_resolution_test.rb
- lib/us_core_test_kit/generated/v3.1.1/document_reference/metadata.yml
- lib/us_core_test_kit/generated/v3.1.1/metadata.yml
- lib/us_core_test_kit/generator/must_support_metadata_extractor.rb
- spec/us_core/reference_test_spec.rb
This PR removes DocumentReference.custodian from MustSupport test. This is based on the US Core 3.1.1 patch using FHIR-28393. This patch is approved by CGP.
This PR also fixed a bug that generator failed due to `nil` value in the _targetProfile extensions.
Verifies that DocumentReference.custodian does not shown in the DocumentReference's MustSupport test
> FI-1764 Remove DocumentReference.custodian from MustSupport

- lib/us_core_test_kit/generated/v5.0.1/condition_problems_health_concerns/metadata.yml
- lib/us_core_test_kit/generated/v5.0.1/metadata.yml
- lib/us_core_test_kit/generated/v5.0.1/observation_sdoh_assessment/metadata.yml
- lib/us_core_test_kit/generated/v5.0.1/observation_social_history/metadata.yml
- lib/us_core_test_kit/generator/value_extractor.rb
This PR fixes GitHub Issue https://github.com/onc-healthit/onc-certification-g10-test-kit/issues/356
Some US Core v5.0.1 profiles have slicing using the same concept. For example: both Observation Social History and Observation SDOH Assessment have and optional slicing on ObservationCategory sdoh.
This causes a validation error because resources from difference profiles are mixed together.
This PR changes
* Remove optional patternCodeablConcept from search definition metadata
US Core v5.0.1 test for Observation Social History and Observation SDOH Assessment shall not search with category value sdoh. The validation tests for Observation Social History and Observation SDOH Assessment shall pass
> FI-1800 Remove values from optional patternCodeablConcept

- lib/us_core_test_kit/generated/v3.1.1/us_core_test_suite.rb
- lib/us_core_test_kit/generated/v4.0.0/us_core_test_suite.rb
- lib/us_core_test_kit/generated/v5.0.1/us_core_test_suite.rb
- lib/us_core_test_kit/generator/templates/suite.rb.erb
- lib/us_core_test_kit/provenance_validator.rb
- spec/us_core/provenance_validator_spec.rb
This PR fixes the US Core part of GitHub issue https://github.com/onc-healthit/onc-certification-g10-test-kit/issues/363
This PR includes
* Remove provenance-1 error message from validator
* Add provenance_validator.rb to validation provenance-1 constraint
* Add unit test for provenance_validator
1. Update reference server to US Core 5 data set.
2. Run US Core 5 test kit.
3. Verify that all Provenance tests pass
> FI-1812 add provenance_validator for provenance-1 constraint

- lib/us_core_test_kit/generated/v4.0.0/medication_request/medication_request_reference_resolution_test.rb
- lib/us_core_test_kit/generated/v4.0.0/medication_request/metadata.yml
- lib/us_core_test_kit/generated/v4.0.0/metadata.yml
- lib/us_core_test_kit/generated/v5.0.1/medication_request/medication_request_reference_resolution_test.rb
- lib/us_core_test_kit/generated/v5.0.1/medication_request/metadata.yml
- lib/us_core_test_kit/generated/v5.0.1/metadata.yml
- lib/us_core_test_kit/generator/must_support_metadata_extractor.rb
This fix Github Issue https://github.com/onc-healthit/onc-certification-g10-test-kit/issues/412
What changes:
* Fix the name [:type] to [:types] in must_support_extractor
* Re-generate US Core v4 and v5
Visual inspect medication_request/metadata
> FI-1928 Fix generator bug for Reference choice

- lib/us_core_test_kit/generated/v3.1.1/metadata.yml
- lib/us_core_test_kit/generated/v3.1.1/patient/metadata.yml
- lib/us_core_test_kit/generated/v3.1.1/patient/patient_must_support_test.rb
- lib/us_core_test_kit/generated/v4.0.0/metadata.yml
- lib/us_core_test_kit/generated/v4.0.0/patient/metadata.yml
- lib/us_core_test_kit/generated/v4.0.0/patient/patient_must_support_test.rb
- lib/us_core_test_kit/generated/v5.0.1/metadata.yml
- lib/us_core_test_kit/generated/v5.0.1/patient/metadata.yml
- lib/us_core_test_kit/generated/v5.0.1/patient/patient_must_support_test.rb
- lib/us_core_test_kit/generator/must_support_metadata_extractor_us_core_3.rb
- lib/us_core_test_kit/generator/must_support_metadata_extractor_us_core_4.rb
- lib/us_core_test_kit/generator/must_support_metadata_extractor_us_core_5.rb
This PR fixes GitHub Issue: https://github.com/onc-healthit/onc-certification-g10-test-kit/issues/416
* Remove `address.period` from Patient MustSupport test for US Core v3, v4, and v5
* Add UCDI choices of `address.period.end or address.use` and `name.period.end or name.use` to Patient's MustSupport test for US Core v3, v4, v5
Patient's previous name is not a MustSupport test in US Core v3 Test Suite and it is added to (g)(10) Certification test as a manual attestation. This change adds previous name test back to US Core v3 Test Suite as a USCDI only test. And corresponding manual attestation will be deprecated. If reviewers think such change has negative effects on the whole (g)(10) test group, we could reverse the change for Patient's previous name
Verify that in US Core v3, v4, v5 …
> Change Patient's previous address and name test

- lib/us_core_test_kit/generator/search_definition_metadata_extractor.rb
There was a binding.pry accidentally left in source.
Remove that line
> Remove binding.pry

- lib/us_core_test_kit/generated/v6.0.0-ballot/metadata.yml
- lib/us_core_test_kit/generated/v6.0.0-ballot/observation_screening_assessment/metadata.yml
- lib/us_core_test_kit/generated/v6.0.0-ballot/procedure/metadata.yml
- lib/us_core_test_kit/generated/v6.0.0-ballot/service_request/metadata.yml
- lib/us_core_test_kit/generated/v6.0.0-ballot/service_request/service_request_must_support_test.rb
- lib/us_core_test_kit/generated/v6.0.0-ballot/service_request/service_request_reference_resolution_test.rb
- lib/us_core_test_kit/generator/must_support_metadata_extractor_us_core_6.rb
Add target_profiles for Procedure.basedOn MustSupport metadata. This is based on the Profile Specific Implementation Guidance:
*The Reason or justification for a referral or consultation is communicated through the [US Core ServiceRequest Profile](http://hl7.org/fhir/us/core/2023Jan/StructureDefinition-us-core-servicerequest.html) which can be linked to the Procedure through the `Procedure.basedOn’ element.
Add ServiceRequest.reasonCode and resonReference as USCDI requirement and MustSupport choice
> FI-1946 Add target_profiles for Procedure.basedOn MustSupport metadata

- README.md
[Ticket # FI-2072](https://oncprojectracking.healthit.gov/support/browse/FI-2072)
Updated README to require 10 GB of available memory for Docker after the validator service encountered a critical OutOfMemory exception when attempting to run the test kit with only 8 GB memory.
Updated to the current year in the license of the README.  
None
> Updated memory requirements and license year

- lib/us_core_test_kit/generated/v6.1.0/medication_dispense/medication_dispense_patient_search_test.rb
- lib/us_core_test_kit/generated/v6.1.0/medication_dispense/medication_dispense_patient_status_search_test.rb
- lib/us_core_test_kit/generated/v6.1.0/medication_dispense/medication_dispense_patient_status_type_search_test.rb
- lib/us_core_test_kit/generator/search_test_generator.rb
- lib/us_core_test_kit/search_test.rb
This PR fixes GitHub Issue: 
https://github.com/onc-healthit/onc-certification-g10-test-kit/issues/460, and
https://github.com/inferno-framework/us-core-test-kit/issues/131
Change Log:
* Update generator using "resource_type" variable instead of constant "MedicationRequest" in test description.
* Update search_test using "resource_type" variable instead of constant "MedicationRequest" when adding _include search parameter
> FI-2212 Fix _include search for MedicationDispense

- config.ru
A change made to the template did not get propogated to the US Core Test Kit that enables users to mount this test kit under non-root.
To replicate, you should be able to follow [these instructions](https://inferno-framework.github.io/inferno-core/deployment/host.html#base-path-configuration) to mount to a non-root path.  Previous to this fix, it would result in a blank page. 
Follow the instructions to mount this to a non-root (e.g. http://localhost/custompath).  After this fix, it should work when you navigate there.  Prior to this fix it will just show a blank page.
> FI-2240 Fix non-root deployment on US Core

- Gemfile.lock
- config/presets/inferno_reference_server_311_preset.json
- config/presets/inferno_reference_server_400_preset.json
- config/presets/inferno_reference_server_501_preset.json
- config/presets/inferno_reference_server_610_preset.json
- lib/us_core_test_kit/custom_groups/smart_app_launch_group.rb
- lib/us_core_test_kit/generated/v3.1.1/us_core_test_suite.rb
- lib/us_core_test_kit/generated/v4.0.0/us_core_test_suite.rb
- lib/us_core_test_kit/generated/v5.0.1/us_core_test_suite.rb
- lib/us_core_test_kit/generated/v6.1.0/us_core_test_suite.rb
- lib/us_core_test_kit/generator/suite_generator.rb
- lib/us_core_test_kit/generator/templates/suite.rb.erb
- lib/us_core_test_kit/us_core_options.rb
- us_core_test_kit.gemspec
Added SMART App Launch tests to US Core test kit since support for SMART App Launch has been a US Core requirement since at least version 3.1.1, but SMART tests are not included in the test kit. Added Standalone and EHR launch tests as optional tests, each containing 4 test groups: SMART discovery (required), SMART ehr/standalone launch (required), SMART openid connect (optional), and smart token refresh (optional). Updated the US core presets so that it contains all the inputs for the SMART app launch tickets as well.
Run the Inferno US Core test kit locally, and run the SMART App Launch tests using the Inferno Reference server preset, and make sure everything passes.
> FI-2370: Add SMART App Launch

- lib/us_core_test_kit/generator/group_metadata.rb
This method is not used currently but better to fix for futhure usage
> fix exclude_search_tests

- lib/us_core_test_kit/generator/group_metadata.rb
The missing require here causes a problem in the g10 tests.
> Add missing require

- lib/us_core_test_kit/generated/v3.1.1/metadata.yml
- lib/us_core_test_kit/generated/v3.1.1/patient/metadata.yml
- lib/us_core_test_kit/generated/v4.0.0/metadata.yml
- lib/us_core_test_kit/generated/v4.0.0/patient/metadata.yml
- lib/us_core_test_kit/generated/v5.0.1/metadata.yml
- lib/us_core_test_kit/generated/v5.0.1/patient/metadata.yml
- lib/us_core_test_kit/generated/v6.1.0/metadata.yml
- lib/us_core_test_kit/generated/v6.1.0/patient/metadata.yml
- lib/us_core_test_kit/generated/v6.1.0/patient/patient_must_support_test.rb
- lib/us_core_test_kit/generated/v7.0.0-ballot/metadata.yml
- lib/us_core_test_kit/generated/v7.0.0-ballot/patient/metadata.yml
- lib/us_core_test_kit/generated/v7.0.0-ballot/patient/patient_must_support_test.rb
- lib/us_core_test_kit/generator/must_support_metadata_extractor_us_core_3.rb
- lib/us_core_test_kit/generator/must_support_metadata_extractor_us_core_4.rb
- lib/us_core_test_kit/generator/must_support_metadata_extractor_us_core_5.rb
- lib/us_core_test_kit/generator/must_support_metadata_extractor_us_core_6.rb
- spec/us_core/must_support_test_spec.rb
This PR fix GitHub issue: https://github.com/onc-healthit/onc-certification-g10-test-kit/issues/496. 
This PR fixed several issues in our current MustSupport test for Patient's previous name and previous address:
* US Core 3/4/5: Add Patient's `name.use`, `name.period.end`, `address.use`, `address.period.end` as USCDI_ONLY MustSpport elements
* US Core 6/7: Change MustSupport element `name.period` to `name.period.end`, and MustSupport element `address.period` to `address.period.end`
* Update unit tests.
All unit tests shall pass
> FI-2534 Fix US Core MS Support for Patient's previous name and previous address

- lib/us_core_test_kit/granular_scope_checker.rb
- spec/us_core/granular_scope_checker_spec.rb
Added inspection of request body if it is a POST request for query parameters.
Wondering about if we will ever expect more in the body than query parameters, i.e. should there be more thorough parsing/decision making here?
Also want to check that POST searches are made to an endpoint that ends in `\_search` every time?  The current spec test uses that endpoint, and I don't think it would impact the functionality, but the spec test wouldn't pass until I added that into the url (fhir_search must automatically add the route when it sees it's a POST?)
Added a spec test that stubs a post request and returns correct resources, and expects test to pass.
> FI-2494 POST capability added to granular scopes

- us_core_test_kit.gemspec
Underscore/dash shenanigans broke the homepage url link: <https://rubygems.org/gems/us_core_test_kit>.
Though I might be the only person using RubyGems search engine over Google's or GitHub's.
`gem build us_core_test_kit.gemspec` for now. I'll check the link sometime after the next release.
> Fix homepage url on RubyGems

- lib/us_core_test_kit/generated/v3.1.1/us_core_test_suite.rb
- lib/us_core_test_kit/generated/v4.0.0/us_core_test_suite.rb
- lib/us_core_test_kit/generated/v5.0.1/us_core_test_suite.rb
- lib/us_core_test_kit/generated/v6.1.0/us_core_test_suite.rb
- lib/us_core_test_kit/generated/v7.0.0-ballot/us_core_test_suite.rb
- lib/us_core_test_kit/generator/templates/suite.rb.erb
This PR ignores this validator error regarding the L/min unit on the Pulse Oximetry profile.
This error is a known issue since US Core 3.1.1 and is documented in the IG itself: https://build.fhir.org/ig/HL7/US-Core/StructureDefinition-us-core-pulse-oximetry.html
> STU Note
> This profile is technically non-conformant with the base FHIR ver 4.0.1 vitals profile which defines a required binding that excludes the concept for L/min for `Observation.component.value(x)`. This is a known issue in and it means validation errors may occur when validating against this version of the US Core Pulse Oximetry Profile. A change request to correct this has been applied to the base FHIR ver 4.3.0 (“Release 4B”).
This error comes from the terminology lookup so it does not occur in g10.
In production the …
> FI-2425: Ignore validator error for L/min unit on Pulse Ox profile

- lib/us_core_test_kit/fhir_resource_navigation.rb
- lib/us_core_test_kit/must_support_test.rb
- spec/us_core/must_support_test_spec.rb
This PR fixes https://oncprojectracking.healthit.gov/support/browse/FI-2611
* Avoid NoMethodFound error when an element does not have expected children path 
* Add unit test with specific usecase
* All unit tests SHALL pass
> FI-2611 Fix MustSupport issue on Coverage.identifier:membershipid.type

- Dockerfile
- lib/us_core_test_kit/search_test.rb
- spec/us_core/search_test_spec.rb
This fixes JIRA FHIR-2687. The problem happens when search parameter targets a primitive value and the resource has an extension on the primitive, for example, instead of 
```
"date": "2024-01-01"
```
server pupulates `date` with extension:
```
"_date": {
"extension": [ {
"url": "http://example.com/extension",
"valueString": "value"
}]
}
```
When Infenro extract search values from returned resourcee, Inferno locates the primitive and tries to conver the "primitve value" into a string. When the value is actually an extension, as shown above, the `to_s` fails.
* Fix search_param_value method so that when the element is a type of Element is skip. This is based on that all search parameters target concrete data types. Data type Element is the base class and not used in any profile directly. …
> FI-2687 Skip find search values from primitive extension

- .env.development
- .env.production
- docker-compose.yml
- lib/us_core_test_kit/generated/v3.1.1/us_core_test_suite.rb
- lib/us_core_test_kit/generated/v4.0.0/us_core_test_suite.rb
- lib/us_core_test_kit/generated/v5.0.1/us_core_test_suite.rb
- lib/us_core_test_kit/generated/v6.1.0/us_core_test_suite.rb
- lib/us_core_test_kit/generated/v7.0.0-ballot/us_core_test_suite.rb
- lib/us_core_test_kit/generator/suite_generator.rb
- lib/us_core_test_kit/generator/templates/suite.rb.erb
Follow-on to #168 . Standardizes the environment variables used for the different test suites, now we can just use the default `FHIR_RESOURCE_VALIDATOR_URL` and remove the `url` line from the validator definition block
Also fixes the docker-compose file to allow running fully in docker, whoops.
There should be no visible impact to the env var change - sessions should start up and work when running via ruby or via docker
> Use default validator env var

- lib/us_core_test_kit/generator/group_metadata.rb
- lib/us_core_test_kit/generator/special_cases.rb
This PR fixes GitHub Issue https://github.com/onc-healthit/onc-certification-g10-test-kit/issues/510
* Move Practitioner from `SEARCHABLE_DELAYED_RESOURCES` to `NON_USCDI_RESOURCE`
* Remove Specimen from `NON_USCDI_RESOURCE` because it is a USCDI v3 data element.
* Update group_metadata logic so that not mandatory patient searches (the one in Specimen) are counted as `no_patient_search`
This can be only tested in (g)(10) test kit. 
* Add us-core-test-kit path to g10 test kit's gem file:
* ```gem 'us_core_test_kit', path: '[path_to]/us-core-test-kit'```
* Run `bundle install`, `inferno service start`, `inferno start`
* Start G10 test with US Core v6.1.0.
* Verify that Practitioner test group (10.41) does not have any search tests.
* Verify that Specimen test group (10.44) does not have any …
> FI-2171 Remove Practitioner from SEARCHABLE_DELAYED_RESOURCES

- lib/us_core_test_kit/custom_groups/base_smart_granular_scopes_group.rb
- lib/us_core_test_kit/custom_groups/granted_granular_scopes_test.rb
- lib/us_core_test_kit/custom_groups/smart_scopes_constants.rb
- lib/us_core_test_kit/custom_groups/v6.1.0/smart_granular_scopes_group.rb
- lib/us_core_test_kit/custom_groups/v7.0.0-ballot/smart_granular_scopes_group.rb
- lib/us_core_test_kit/generated/v6.1.0/granular_scopes1_group.rb
- lib/us_core_test_kit/generated/v6.1.0/observation_granular_scope1_group.rb
- spec/us_core/granted_granular_scopes_test_spec.rb
This branch adds tests to verify that the required granular scopes were granted.
Run one of the granular scope launches against the reference server. When the reference server allows you to select which scopes to grant, deselect some of the granular scopes, and test will fail.
> FI-2456: Verify granular scopes

- lib/us_core_test_kit/provenance_validator.rb
- spec/us_core/provenance_validator_spec.rb
This is fix for GitHub issue https://github.com/onc-healthit/onc-certification-g10-test-kit/issues/514
* Add & operator to agent.who
* Add unit tests to ensure when agent, agent.who, or agent.who.reference is nil, additional validation in ProvenanceValidator does not throw error
* all unit tests pass
> FI-2790 Fix error caused by agent.who is nil

- lib/us_core_test_kit/fhir_resource_navigation.rb
- lib/us_core_test_kit/must_support_test.rb
- lib/us_core_test_kit/primitive_type.rb
- lib/us_core_test_kit/search_test.rb
- spec/fixtures/QuestionnaireResponse.json
- spec/us_core/must_support_test_spec.rb
- spec/us_core/search_test_spec.rb
This PR fixes a new issue reported on GitHub issue https://github.com/onc-healthit/onc-certification-g10-test-kit/issues/411
Previous solution had an assumption that an primitive element has either value or extension but not both. This has been proved wrong.
This PR handles primitive element with either value, or extensions, or both.
* Add PrimitiveType inherited from FHIR::Element
* Update logic in several components to handle primitive element with both value and extension
* Update unit tests
All unit tests shall pass
All integration tests with reference server shall pass
> FI-2762 Add PrimitiveType class

- lib/us_core_test_kit/custom_groups/smart_scopes_constants.rb
- lib/us_core_test_kit/custom_groups/v6.1.0/smart_granular_scopes_group.rb
- lib/us_core_test_kit/generated/v6.1.0/condition_granular_scope1_group.rb
- lib/us_core_test_kit/generated/v6.1.0/condition_granular_scope2_group.rb
- lib/us_core_test_kit/generated/v6.1.0/granular_scope_tests/condition/metadata.yml
- lib/us_core_test_kit/generated/v6.1.0/granular_scope_tests/observation/metadata.yml
- lib/us_core_test_kit/generated/v6.1.0/granular_scopes1_group.rb
- lib/us_core_test_kit/generated/v6.1.0/granular_scopes2_group.rb
- lib/us_core_test_kit/generated/v6.1.0/metadata.yml
- lib/us_core_test_kit/generated/v6.1.0/observation_granular_scope2_group.rb
- lib/us_core_test_kit/generated/v6.1.0/us_core_test_suite.rb
- lib/us_core_test_kit/generated/v7.0.0-ballot/us_core_test_suite.rb
- lib/us_core_test_kit/generator/granular_scope_group_generator.rb
- lib/us_core_test_kit/generator/granular_scope_resource_type_group_generator.rb
- lib/us_core_test_kit/generator/granular_scope_test_generator.rb
- lib/us_core_test_kit/generator/suite_generator.rb
- lib/us_core_test_kit/generator/templates/suite.rb.erb
This branch reverts #169, so granular scopes in US Core 6.1.0 will again be tested using two groups with the scopes split between the groups rather than testing support for all granular scopes within a single group.
If you run US Core 6.1.0 with SMART App Launch 2, you should see the two granular scope groups using distinct sets of scopes.
> FI-2818: Revert granular scope change

- lib/us_core_test_kit/custom_groups/capability_statement/instantiate_test.rb
- lib/us_core_test_kit/custom_groups/capability_statement/profile_support_test.rb
- spec/us_core/instantiate_test_spec.rb
- spec/us_core/profile_support_test_spec.rb
This PR fixes GitHub issue https://github.com/onc-healthit/onc-certification-g10-test-kit/issues/525
* If CapabilityStatement's instantiate and supportedProfile elements contains canonical url with trailing version number, tests ignore the version number and use the main url part for testing.
* Add unit tests
All unit tests pass
> FI-2497 Handle Canonical URL trailing version

- lib/us_core_test_kit/custom_groups/v7.0.0/smart_app_launch_group.rb
- lib/us_core_test_kit/custom_groups/v7.0.0/smart_discovery_stu2_group.rb
- lib/us_core_test_kit/generated/v7.0.0/us_core_test_suite.rb
- lib/us_core_test_kit/generator/suite_generator.rb
- lib/us_core_test_kit/generator/templates/suite.rb.erb
This ticket fixed FI-2859.
* Add US Core v7 specific test group for smart_app_launch and smart_discovery_stu2
* Update suite_generator and suite_template to add smart_app_lauch group based on US Core version.
* Run US Core Test Kit
* Start US Core v7 + SMART v2
* Verify that "Well-known configuration declares support for Additional US Core Required capabilities" is shown in SMART on FHIR Discovery test group for both stand along launch and EHR launch (1.3.1 and 1.4.1)
* Start US Core v6 + SMART v2
* Verify that "Well-known configuration declares support for Additional US Core Required capabilities" is shown in test group 1.3.1 and 1.4.1
> FI-2859 Fix issue where v7 capability test added to old uscore version

- lib/us_core_test_kit/granular_scope_read_test.rb
- spec/us_core/granular_scope_read_spec.rb
When finding a resource which should be able to be read using the currently granted granular scopes, currently only the code of the granular scope is used for matching. It needs to match based on both the code and system of the granular scope.
After fixing this bug, it was necessary to update some unit test data to match this more stringent requirement.
> FI-2955: Include code system when checking for resources to read

- lib/us_core_test_kit/granular_scope_search_test.rb
- spec/us_core/granular_scope_search_spec.rb
Add guards against other returned resources within granular searches, such as OperationOutcome.
> FI-3042 Don't Include OperationOutcomes when Checking Granular Scope Search Results

- lib/us_core_test_kit/custom_groups/granted_granular_scopes_test.rb
- spec/us_core/granted_granular_scopes_test_spec.rb
This branch fixes a bug which caused tests to fail if a server returned separate read and search granular scopes.
> FI-3039 Add Support for Separately Returned Granular Scopes

- README.md
- lib/us_core_test_kit/generated/v6.1.0/metadata.yml
- lib/us_core_test_kit/generated/v6.1.0/smokingstatus/metadata.yml
- lib/us_core_test_kit/generated/v6.1.0/smokingstatus/smokingstatus_must_support_test.rb
- lib/us_core_test_kit/generated/v6.1.0/us_core_test_suite.rb
- lib/us_core_test_kit/generator/must_support_metadata_extractor_us_core_6.rb
- lib/us_core_test_kit/generator/must_support_metadata_extractor_us_core_7.rb
- lib/us_core_test_kit/generator/suite_generator.rb
- lib/us_core_test_kit/generator/templates/suite.rb.erb
This PR fixed this Github issue: https://github.com/onc-healthit/onc-certification-g10-test-kit/issues/560
* Remove MustSupport slice: effectiveDateTime
* Add MustSuport element: effective[x]
* Add version specific error fileter to allow effectivePeriod
Current Inferno reference server does not have effectivePeriod for SmokingStatus. Will update server data to support this test case.
> FI-3060 Add MustSuport choice for Observation.effective[x]

- lib/us_core_test_kit/generated/v3.1.1/us_core_test_suite.rb
- lib/us_core_test_kit/generated/v4.0.0/us_core_test_suite.rb
- lib/us_core_test_kit/generated/v5.0.1/us_core_test_suite.rb
- lib/us_core_test_kit/generated/v6.1.0/us_core_test_suite.rb
- lib/us_core_test_kit/generated/v7.0.0/us_core_test_suite.rb
- lib/us_core_test_kit/generator/suite_generator.rb
- lib/us_core_test_kit/generator/templates/suite.rb.erb
This PR fixes GitHub Issue https://github.com/onc-healthit/onc-certification-g10-test-kit/issues/573. The issue is casued by that US Core has two fileters: `VALIDATION_MESSAGE_FILTERS` and `VERSION_SPECIFIC_MESSAGE_FILTERS`. (g)(10) test kit uses `VALIDATION_MESSAGE_FILTERS` only.
Combine `VALIDATION_MESSAGE_FILTERS` and `VERSION_SPECIFIC_MESSAGE_FILTERS` so there's no code change required in (g)(10) test kit.
* Running US Core Test Kit v3.1.1 - 6.1.0 using reference server.
> FI3079 Combine general filter and version specific filter

- lib/us_core_test_kit/custom_groups/v3.1.1/capability_statement_group.rb
- lib/us_core_test_kit/custom_groups/v3.1.1/resource_support_test.rb
- spec/us_core/us_core_v311_resource_support_test_spec.rb
US Core v3.1.1 has a special CapabilityStatement resource support test which verifies that server suports at least Patient + 1 resources. For US Core v4.0.0, this requirement is changed to server supports US Core Patient + 1 US Core profiles. The orginal resource support test for US Core v311 test suite accidentally had the same id as the one in US Core v4+ test suite.
* Rename v3.1.1's profile_support_test.rb to resource_support_test.rb
* Change the test id for resource_support_test to match version and purpose
* All unit test shall pass
* Running US Core 3.1.1 test suite using default reference server. CapabilityStatement test group (test group 2.1) shall pass
> Rename US Core v3.1.1 profile support test to resource support test

- lib/us_core_test_kit/generated/v6.1.0/diagnostic_report_note/diagnostic_report_note_must_support_test.rb
- lib/us_core_test_kit/generated/v6.1.0/diagnostic_report_note/diagnostic_report_note_reference_resolution_test.rb
- lib/us_core_test_kit/generated/v6.1.0/diagnostic_report_note/metadata.yml
- lib/us_core_test_kit/generated/v6.1.0/metadata.yml
- lib/us_core_test_kit/generated/v7.0.0/diagnostic_report_note/diagnostic_report_note_must_support_test.rb
- lib/us_core_test_kit/generated/v7.0.0/diagnostic_report_note/diagnostic_report_note_reference_resolution_test.rb
- lib/us_core_test_kit/generated/v7.0.0/diagnostic_report_note/metadata.yml
- lib/us_core_test_kit/generated/v7.0.0/metadata.yml
- lib/us_core_test_kit/generator/must_support_metadata_extractor_us_core_6.rb
- lib/us_core_test_kit/generator/must_support_metadata_extractor_us_core_7.rb
This PR fixes JIRA ticket FI-3421 Remove media and media.link from DiagnosticReport's MustSupport list
Start US Core Test Kit for v6.1.0:
Expand Test: 2.10.10 "All must support elements are provided in the DiagnosticReport resources returned"
Go to About page
Verify that `DiagnosticReport.media` and `DiagnosticReport.media.link` are not in the list
Expand Test 2.10.11 "MustSupport references within DiagnosticReport resources are valid"
Go to About page
Verify that `DiagnosticReport.media.link` is not in the list
Start US Core Test Kit for v7.0.0
Do the same verification as US Core v6.1.0
> FI-3421 Remove media and media.link from DiagnosticReport's MustSupport list

- lib/us_core_test_kit/generated/v7.0.0/diagnostic_report_note/diagnostic_report_note_must_support_test.rb
- lib/us_core_test_kit/generated/v7.0.0/diagnostic_report_note/diagnostic_report_note_reference_resolution_test.rb
- lib/us_core_test_kit/generated/v7.0.0/diagnostic_report_note/metadata.yml
- lib/us_core_test_kit/generated/v7.0.0/metadata.yml
- lib/us_core_test_kit/generated/v7.0.0/us_core_test_suite.rb
- lib/us_core_test_kit/generator/must_support_metadata_extractor_us_core_6.rb
- lib/us_core_test_kit/generator/must_support_metadata_extractor_us_core_7.rb
- lib/us_core_test_kit/generator/templates/suite.rb.erb
US Core v6.1.0 patch [FHIR-46240](https://jira.hl7.org/browse/FHIR-46240) was incorrectly applied to US Core v7 test kit. We temporarily reversed this change till HL7 CGP WG appove this patch for US Core v7 usage.
Run US Core v7 test kit. 
Verify that `media` and `media.link` shows in test 2.10.11 "All must support elements are provided in the DiagnosticReport resources returned"
Verify that `media.link` shows in test 2.10.12 "MustSupport references within DiagnosticReport resources are valid"
> FI-3445 Add media and media.link back to US Core v7 DiagnosticReport must support

- lib/us_core_test_kit/search_test.rb
- spec/us_core/search_test_spec.rb
This PR fixes GitHub Issue https://github.com/onc-healthit/onc-certification-g10-test-kit/issues/589
* Add a logic to check if Reference.reference is empty 
* Add a unit test
All unit test pass
> FI-3474 Add a check if Reference.reference is empty before processing

- lib/us_core_test_kit/generated/v6.1.0/us_core_test_suite.rb
- lib/us_core_test_kit/generator/suite_generator.rb
This updates GitHub Issue https://github.com/onc-healthit/onc-certification-g10-test-kit/issues/573. The previous solution does not hand effectivePeriod.start. This adds that subelement into the regex.
> FI-3486 Add validation message filter for US Core 6 Observation Smoking Status effectivePeriod.start

- lib/us_core_test_kit/generated/v6.1.0/condition_granular_scope1_group.rb
- lib/us_core_test_kit/generated/v6.1.0/condition_granular_scope2_group.rb
- lib/us_core_test_kit/generated/v6.1.0/observation_granular_scope1_group.rb
- lib/us_core_test_kit/generated/v6.1.0/observation_granular_scope2_group.rb
- lib/us_core_test_kit/generated/v7.0.0/condition_granular_scope1_group.rb
- lib/us_core_test_kit/generated/v7.0.0/condition_granular_scope2_group.rb
- lib/us_core_test_kit/generated/v7.0.0/observation_granular_scope1_group.rb
- lib/us_core_test_kit/generated/v7.0.0/observation_granular_scope2_group.rb
- lib/us_core_test_kit/generator/granular_scope_resource_type_group_generator.rb
This PR fixes FI-3133 Test name typo for granular scope tests.
The root is that both the granular scope class and granular scope template have trailing term "Tests".
This PR can be reviewed after SVAP 2024.
* Remove the trailing "Tests" from title property
* Add misisng id into generator template.
Verify 9.14.2.2 and 9.14.2.3 test does not have "Tests Tests" in their test title.
> FI-3133 Test name typo for granular scope tests.

- README.md
The link to Inferno should just go straight to the Inferno Framework landing page.  Also add the fact that v7.0.0 is supported for testing.
> Improve README.md content and links

- README.md
The relative link to the wiki didn't work in the README.  Fixes that.  Other links throughout seem ok.
> Fix link in the README.

- README.md
- docs/README.md
Unfortunately no relative links work at all from the README.md to the wiki, so i have to use an absolute link (which makes sense as that absolute link is the singular 'home' of the manual).
I also noticed this time that the issues link didn't point to the right spot.
Sorry for the repetitive PRs, this is challenging to evaluate until it is deployed to the wiki.
> Docs update; broken links.

- .github/workflows/publish-docs-wiki.yml
This applies the improved docs publishing workflow that we have already incorporated into the g10 test kit.  It makes it easier to preview updates to the documentation that get published to the wiki.  I'd like to get this in here before i add one final PR for a last round of US Core Test Kit documentation updates.
I do not believe testing is necessary as this was tested in the g10 repo.
> FI-3642 Update docs publishing workflow to US Core test kit

- README.md
- docs/Overview.md
- docs/README.md
- docs/Technical-Overview.md
- docs/Version-Update-Guide.md
- docs/_Footer.md
- docs/_Sidebar.md
Incorporates addiitonal improvements based on improvements to the g10 docs.
I proactively synched these up to the [wiki as a preview](/inferno-framework/us-core-test-kit/wiki) in case you would like to take a look what it looks like.  If there are major problems and this ticket is rejected, it can be resynched to the docs on main by running [this workflow](https://github.com/inferno-framework/us-core-test-kit/actions/workflows/publish-docs-wiki.yml) manually.
> Additional US Core Docs update

- Gemfile.lock
- lib/us_core_test_kit/generated/v3.1.1/us_core_test_suite.rb
- lib/us_core_test_kit/generated/v4.0.0/us_core_test_suite.rb
- lib/us_core_test_kit/generated/v5.0.1/us_core_test_suite.rb
- lib/us_core_test_kit/generated/v6.1.0/us_core_test_suite.rb
- lib/us_core_test_kit/generated/v7.0.0/us_core_test_suite.rb
- lib/us_core_test_kit/generator/templates/suite.rb.erb
- us_core_test_kit.gemspec
inferno.healthit.gov defaults to smart v2 for all suites in US Core.  See https://inferno.healthit.gov/test-kits/us-core/
This updates our suite options to be consistent with that so there is no behavior change when we migrate over to the new method of leveraging test kit metadata on platform apps.
This operates under the assumption that we want to use this version of smart as the default, but it seems reasonable to me.  Feel free to disagree though -- we don't have to merge this.
This includes functionality provided by the new v0.6.4 inferno core release, which is why the gemspec reflects that as a minimum version.
The only way to test right now is to launch the app and check the API responses that come back; SMART App Launch 2 should be the default for all US Core suites.  A later …
> FI-3754 Default suites to use smart v2.0.0 in new metadata

- lib/us_core_test_kit/generated/v3.1.1/us_core_test_suite.rb
- lib/us_core_test_kit/generated/v4.0.0/us_core_test_suite.rb
- lib/us_core_test_kit/generated/v5.0.1/us_core_test_suite.rb
- lib/us_core_test_kit/generated/v6.1.0/us_core_test_suite.rb
- lib/us_core_test_kit/generated/v7.0.0/us_core_test_suite.rb
- lib/us_core_test_kit/generator/templates/suite.rb.erb
This is linked to GitHub Issue https://github.com/onc-healthit/onc-certification-g10-test-kit/issues/620
Previously, when the server sends an Observation BMI resource with dataAbsentReason, the validator would throw a validation error:
Observation: Slice 'Observation.value[x]:valueQuantity': a matching slice is required, but not found (from [http://hl7.org/fhir/StructureDefinition/bmi|4.0.1|http://hl7.org/fhir/StructureDefinition/bmi%7C4.0.1]).
The reason is that all resources have to be valid not only to its declared profiles but also to corresponding FHIR resource type and FHIR core profiles. When the validator validates a US Core BMI observation resource, it validates it using both US Core BMI profile and FHIR BMI profile. US Core BMI profile inherits from FHIR vital-signs profile …
> FI-3752: Observation BMI dataAbsentReason Validation Filter

- lib/us_core_test_kit/granular_scope_search_test.rb
- lib/us_core_test_kit/search_test.rb
- remove `USCoreTestKit::SearchTest#fetch_all_bundled_resources` which is now defined in core
- implement `fetch_and_assert_all_bundled_resources`, which wraps the former function and adds the assertion statements the original definition had
- fix rspec tests so they pass with new functions
1. Checkout branch
2. `bundle exec rspec`
> Remove USCoreTestKit::SearchTest#fetch_all_bundled_resources

- .env.test
- spec/us_core/validation_test_spec.rb
Add unit test to ensure that the validation message filter for the BMI dataAbsentReason validation error is working as expected.
Run spec tests and ensure they all pass
> FI-3765: Validation Message Filter Unit Test

- lib/us_core_test_kit/custom_groups/v3.1.1/capability_statement_group.rb
- lib/us_core_test_kit/custom_groups/v3.1.1/resource_support_test.rb
- lib/us_core_test_kit/custom_groups/v4.0.0/capability_statement_group.rb
- lib/us_core_test_kit/custom_groups/v5.0.1/capability_statement_group.rb
- lib/us_core_test_kit/custom_groups/v6.1.0/capability_statement_group.rb
- lib/us_core_test_kit/custom_groups/v7.0.0/capability_statement_group.rb
- The Capability Statement group description referenced SMART on FHIR requirements and detailed saved information that wasn't actually saved by the tests.
- In the 3.1.1 version, the word "Resource" was misspelled in the test title "Capability Statement lists support for required US Core Resoruce Types".
- Run the 3.1.1 tests and verify that the spelling has been corrected in the title of test 2.1.05
- Run all versions of the tests and verify that the Capability Statement group description does not reference SMART on FHIR or saving any information
> FI-3879: Typo and outdated details in Capability Statement Tests

- .github/workflows/ruby.yml
This PR adds a `verify-test-generation` job to CI to ensure generated tests are up to date. The job runs `bundle exec rake us_core:generate` and fails if there are uncommitted changes.
> FI-3292: Add CI job to verify test generation is up to date

- lib/us_core_test_kit/practitioner_address_test.rb
This PR fixes FI-4061 Avoid purple error when there is no practitioner references. 
When there is no references to Practitioner resource, the line
```
references = scratch.dig(:references, 'Practitioner')
```
return `nil` instead of `[]`
This PR use safe navigation to catch `nil` instead of throwing puple error.
> FI-4061 Avoid purple error when there is no practitioner references

- lib/us_core_test_kit/client/generated/v3.1.1/us_core_client_test_suite.rb
- lib/us_core_test_kit/client/generated/v3.1.1/wait_group.rb
- lib/us_core_test_kit/client/generated/v4.0.0/us_core_client_test_suite.rb
- lib/us_core_test_kit/client/generated/v4.0.0/wait_group.rb
- lib/us_core_test_kit/client/generated/v5.0.1/us_core_client_test_suite.rb
- lib/us_core_test_kit/client/generated/v5.0.1/wait_group.rb
- lib/us_core_test_kit/client/generated/v6.1.0/us_core_client_test_suite.rb
- lib/us_core_test_kit/client/generated/v6.1.0/wait_group.rb
- lib/us_core_test_kit/client/generated/v7.0.0/us_core_client_test_suite.rb
- lib/us_core_test_kit/client/generated/v7.0.0/wait_group.rb
- lib/us_core_test_kit/client/generator/suite_generator.rb
- lib/us_core_test_kit/client/generator/templates/wait_group.rb.erb
When the client data was finalized, the test patient's mrn identifier system was [updated](https://github.com/inferno-framework/inferno-reference-server-data/pull/2/commits/47a9a554e7e1edf70b02fccb54a7fc6159895e43#diff-8ec787cf201c51ed40c6c97aa7d3ab3a995096c1b502f13e5a65414b9835d576L92) from `Inferno` to `urn:inferno:mrn`. This updates the documentation to match.
1. Start a session for US Core Client v7.0.0 and verify that in the suite documentation under the "Quick Start" section indicates in the patient demographic list that "urn:inferno:mrn" as the Member Identifier's system.
2. Run the tests using the "Demo: Run against the US Core Server Suite" preset and in the second wait dialog, check that the demographics list has been similarly updated.
3. Make sure that you have an instance of …
> Fix client target patient MRN system

- lib/us_core_test_kit/client/generated/v3.1.1/read_endpoint.rb
- lib/us_core_test_kit/client/generated/v3.1.1/search_endpoint.rb
- lib/us_core_test_kit/client/generated/v4.0.0/read_endpoint.rb
- lib/us_core_test_kit/client/generated/v4.0.0/search_endpoint.rb
- lib/us_core_test_kit/client/generated/v5.0.1/read_endpoint.rb
- lib/us_core_test_kit/client/generated/v5.0.1/search_endpoint.rb
- lib/us_core_test_kit/client/generated/v6.1.0/read_endpoint.rb
- lib/us_core_test_kit/client/generated/v6.1.0/search_endpoint.rb
- lib/us_core_test_kit/client/generated/v7.0.0/read_endpoint.rb
- lib/us_core_test_kit/client/generated/v7.0.0/search_endpoint.rb
- lib/us_core_test_kit/client/generator/templates/read_endpoint.rb.erb
- lib/us_core_test_kit/client/generator/templates/search_endpoint.rb.erb
- lib/us_core_test_kit/client/server_proxy.rb
Previously, the client tests returned only the status and response body when proxying requests to the inferno reference server. Now, it returns modified headers and also updates links to use the test suite's host and base fhir path.
Run the client tests, make a FHIR request, and verify that responses returned by the client suite include appropriate content-type headers (e.g., application/fhir+json). Minimal test:
- make sure that the inferno-reference-server is running on port 8080
- start an instance of the US Core client v7.0.0 suite.
- select the "Demo: run against the server tests" preset
- Run all tests, clicking through the first wait dialog to confirm setup.
- in another tab, start an instance of test US Core server v7.0.0 suite
- select the "Demo: run against the client tests" …
> Improve Proxied Responses

- lib/us_core_test_kit/generated/v3.1.1/us_core_test_suite.rb
- lib/us_core_test_kit/generated/v4.0.0/us_core_test_suite.rb
- lib/us_core_test_kit/generated/v5.0.1/us_core_test_suite.rb
- lib/us_core_test_kit/generated/v6.1.0/us_core_test_suite.rb
- lib/us_core_test_kit/generated/v7.0.0/us_core_test_suite.rb
- lib/us_core_test_kit/generator/templates/suite.rb.erb
This branch updates the validator message filters to match updated messages in the new version of the validator.
In inferno_core, run the follwing command in the `validator` directory:
```sh
docker buildx build --platform linux/arm64,linux/amd64 --build-arg "PROJECT_VERSION=1.0.66" --tag "infernocommunity/inferno-resource-validator:1.0.66" --tag infernocommunity/inferno-resource-validator:latest --load .
```
In `docker-compose.background.yml`, update the image for the `hl7_validator_service` to `image: infernocommunity/inferno-resource-validator:1.0.66`.
If you perform these steps and run these tests on the `main` branch, you will see new validator errors, but those errors will be resolved on this branch.
You can also update `docker-compose.background.yml` in g10, and in the g10 Gemfile, …
> FI-4174: Update filters for validator update

- lib/us_core_test_kit/fhir_resource_navigation.rb
- lib/us_core_test_kit/must_support_test.rb
- lib/us_core_test_kit/primitive_type.rb
- lib/us_core_test_kit/reference_resolution_test.rb
- lib/us_core_test_kit/resource_search_param_checker.rb
- lib/us_core_test_kit/search_test.rb
This branch restores the constants for `FHIRResourceNavigation` and `PrimitiveType` so that the switch to the behavior defined in inferno core is not a breaking change.
> FI-4194: Restore FHIRResourceNavigation and PrimitiveType constants
